### ISSUE TITLE
Can we use this dataset without downloading?

### ISSUE THREAD

**Issue by sanyalsunny111** [kakaobrain/coyo-dataset#1]
Dear Authors,

Thank you for the great effort in curating this very interesting dataset. I am wondering if there is a way one can use this dataset without downloading it say with/without huggingface hub? if yes please let me know how?

**Comment by mwbyeon** [comment]
Hi, @sanyalsunny111 

Thank you for your interest in our dataset.

Images included in the COYO dataset must be individually downloaded to be used for training. Due to licensing issues, we cannot provide any files with images (such as webdataset or tfrecord).

If this is not the answer you want, please reopen the issue.
Thank you.
